[[task]]
TaskName = "UwbTracking"
Id = 11
OutDoor = false
DepsNav2LifecycleNodes = ["lifecycle_manager_navigation"]
DepsLifecycleNodes = ["camera/camera", "mivinsfollowing", "mcr_uwb"]

[[task]]
TaskName = "LaserMapping"
Id = 5
OutDoor = false
DepsNav2LifecycleNodes = ["lifecycle_manager_laser_mapping"]
DepsLifecycleNodes = []

[[task]]
TaskName = "VisionTracking"
Id = 13
OutDoor = false
DepsNav2LifecycleNodes = ["lifecycle_manager_navigation"]
DepsLifecycleNodes = ["camera/camera", "vision_manager", "tracking"]

[[task]]
TaskName = "ResetNav"
Id = 0
OutDoor = false
DepsNav2LifecycleNodes = ["lifecycle_manager_navigation"]
DepsLifecycleNodes = ["camera/camera", "mivinsfollowing", "mcr_uwb"]


# [[task]]
# TaskName = "VisMapping"
# Id = 5
# OutDoor = true
# DepsNav2LifecycleNodes = ["lifecycle_manager_laser_mapping"]
# DepsLifecycleNodes = [""]