[[task]]
TaskName = "UwbTracking"
Id = 11
OutDoor = false
DepsNav2LifecycleNodes = ["lifecycle_manager_navigation", "lifecycle_manager_mcr_uwb"]
DepsLifecycleNodes = [""]

[[task]]
TaskName = "LaserMapping"
Id = 5
OutDoor = false
DepsNav2LifecycleNodes = ["lifecycle_manager_laser_mapping"]
DepsLifecycleNodes = [""]

[[task]]
TaskName = "VisionTracking"
Id = 13
OutDoor = false
DepsNav2LifecycleNodes = [""]
DepsLifecycleNodes = [""]

# [[task]]
# TaskName = "VisMapping"
# Id = 5
# OutDoor = true
# DepsNav2LifecycleNodes = ["lifecycle_manager_laser_mapping"]
# DepsLifecycleNodes = [""]